name: Generar Wallpapers JSON Automatico

on:
  push:
    paths:
      - 'img/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar libreria de imagenes
        run: pip install Pillow

      - name: Ejecutar script generador
        run: python generador.py

      - name: Guardar wallpapers.json en GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wallpapers.json
          git commit -m "Auto-actualizacion de wallpapers.json con resolucion real" || echo "Sin cambios"
          git push
